# common params
project: 2d-sds-benchmark

seed: 0
device: cuda

name: ???
group: ???
note: ???
tags: []

uid: "${now:%Y-%m-%d|%H-%M-%S}|${note}"

output_path: "./output/${name}/${uid}"

iterations: 2000
log_interval: 200

typecheck: false

save_code_snapshot: true

wandb:
  project: ${project}
  name: ${uid}
  group: ${group}
  entity: firefly-ustc
  sync_tensorboard: true
  notes: ${note}
  tags: ${tags}

hydra:
  run:
    dir: ${output_path}
