name: sds
group: ${name}
note: ""

defaults:
  - base
  - rasterizer: gaussian_2d
  - wt_schedule: dreamfusion
  - algorithm: sds_algorithm
  - _self_  # override the default values with the values below

prompt: "a photograph of an astronaut riding a horse."
neg_prompt: ""

algorithm:
  guidance_scale: 7.5

rasterizer:
  batch_size: 2
  num_points: 50000
