name: vsd
group: ${name}
note: ""

defaults:
  - base
  - rasterizer: pixels
  - wt_schedule: dreamfusion
  - algorithm: vsd_algorithm
  - _self_  # override the default values with the values below

prompt: "a photograph of an astronaut riding a horse."
neg_prompt: ""

algorithm:
  optimizer:
    opt_args:
      lr: 0.0001

rasterizer:
  batch_size: 4
  optimizer:
    opt_args:
      lr: 0.05
